---
title: "Assignment 1"
author: "Nathan Grimes"
date: "1/12/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,warning = FALSE,message=FALSE)

library(tidyverse)
library(lubridate)
library(patchwork)
library(AICcmodavg)
library(caret)
```

## Task 1 Data Summary

We are tasked to present amphibian abundance data from the Sierra Lakes Inventory Project.



```{r dataimport}
amphibian_raw<-readxl::read_excel("sierra_amphibians.xlsx")
```

```{r tidytask}
ylfrog<-amphibian_raw %>% 
  filter(amphibian_life_stage!="EggMass" & amphibian_species=="RAMU") %>% 
  mutate(survey_date=as.Date(survey_date)) %>% 
  mutate(year=year(survey_date)) %>% 
  group_by(year,amphibian_life_stage) %>% 
  summarize(total=sum(amphibian_number,na.rm = TRUE))

p1<-ggplot(data=ylfrog,aes(x=amphibian_life_stage,y=total))+
  geom_col(aes(fill=as.factor(year)),position="dodge")+
  scale_fill_viridis_d(name="Year")+
  xlab("Life Stage")+
  ylab("Observed Count")+
  theme_classic()

```




```{r tidyadjust}
ylfrogt2<-amphibian_raw %>% 
    filter(amphibian_life_stage %in% c("Adult","SubAdult") & amphibian_species=="RAMU") %>% 
  group_by(lake_id) %>% 
  summarize(total=sum(amphibian_number,na.rm=TRUE)) %>% 
  arrange(desc(total)) %>% 
  head(n=5) %>% 
  mutate(lake_id=sub("^","Lake ",lake_id))

p2<-ggplot(ylfrogt2,aes(x=fct_reorder(lake_id,total),y=total,fill=factor(lake_id)))+
  geom_col()+
  scale_fill_viridis_d()+
  theme_classic()+
  xlab("")+
  ylab("Observed Count")+
  theme(legend.position = "none")
```

```{r plotcombine}
p1/p2
```

## Task 2 Model Selection

### AIC

```{r seawater_data}

seawater_raw<-read.csv("calcofi_seawater_samples.csv",sep=",")

#Create the models

f1=o2sat~t_deg_c+salinity+po4u_m
f2=o2sat~t_deg_c+salinity+po4u_m+depth_m

model1<-lm(o2sat~t_deg_c+salinity+po4u_m,data=seawater_raw)
model2<-lm(o2sat~t_deg_c+salinity+po4u_m+depth_m,data=seawater_raw)

#Combine into list and provide names to make the combined AIC tab function work smoother

models<-list(model1,model2)
mod.names<-c("no.depth","depth")
aictab(cand.set=models,modnames=mod.names)
```

Select the models based on AIC performance. The linear model including depth performed significantly better based on the $\Delta AIC$ greater than 2. 

### BIC

```{r}
bictab(models,mod.names)
```

### Use Caret

```{r CV}
set.seed(123) #Don't want the computer to shift the random breaks everytime we knit

#Use built in functions to create the training section partitions
train.control<-trainControl(method="repeatedcv",number=10,repeats = 3)


#Train the model with the training sets
CVmodel1<-train(o2sat~t_deg_c+salinity+po4u_m,data=seawater_raw,method="lm",trControl=train.control)


#Check Results
results_CV1<-CVmodel1$results$RMSE

#Repeat for the second model on the same training data

CVmodel2<-train(o2sat~t_deg_c+salinity+po4u_m+depth_m,data=seawater_raw,method="lm",trControl=train.control)


results_CV2<-CVmodel2$results$RMSE

print(results_CV1,results_CV2)

# Choose a model in this case model 1 performs slightly better and test on the whole dataset

final_model<-lm(o2sat~t_deg_c+salinity+po4u_m+depth_m,data=seawater_raw)

summary(final_model)
```

### Use a for loop

```{r}

calc_rmse <- function(x, y) {
  rmse <- (x - y)^2 %>% mean() %>% sqrt()
  return(rmse)
}

folds=10

n_iter=10  # do folds 10 times

fold_vec=rep(1:folds,length.out=nrow(seawater_raw)*n_iter)


fold_mat=matrix(fold_vec,ncol=n_iter)

samp=as.data.frame(fold_mat) %>% 
  map(.x=.,~sample(.x,size=nrow(seawater_raw),replace=FALSE))

#Set up storage matrices

rmse_df<-data.frame()

for(j in 1:n_iter){
  for(i in 1:folds){
  kfold_test_df<-seawater_raw %>% 
    mutate(group=samp[[j]]) %>% 
    filter(group==i)
  
   kfold_train_df<-seawater_raw %>% 
    mutate(group=samp[[j]]) %>% 
    filter(group!=i)
   
   ## Train models
   
   kfold_lm1=lm(f1,data=kfold_train_df)
   kfold_lm2=lm(f2,data=kfold_train_df)
  
   # Test
   kfold_pred_df<-kfold_test_df %>% 
     mutate(mdl1=predict(kfold_lm1,.),
            mdl2=predict(kfold_lm2,.))
   
   kfold_rmse=kfold_pred_df %>% 
     summarize(rmse_mdl1=calc_rmse(mdl1,o2sat),
               rmse_mdl2=calc_rmse(mdl2,o2sat),
               test_gp=i,
               iter=j)
   
   rmse_df<-rbind(rmse_df,kfold_rmse)
  
  }

}

rmse_df %>% 
  summarize(mean_mdl1 = mean(rmse_mdl1),
            mean_mdl2=mean(rmse_mdl2))


```


### Use tidymodels